name: Automated Crawl Mohub
on: workflow_dispatch
jobs:
  crawl_frb:
    env:
      id: frb
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
        - '3.8'
    steps:
    - name: checkout
      uses: actions/checkout@v3
      with:
        ref: ${{ github.ref }}
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: python -m pip install --upgrade pip && pip install -r requirements.txt
    - name: Crawl feed
      working-directory: ./
      run: python main.py -i $id
    - name: Upload crawl data as artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.id }}_data
        path: ${{ env.id}}.json
  crawl_msu:
    env:
      id: msu
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
        - '3.8'
    steps:
    - name: checkout
      uses: actions/checkout@v3
      with:
        ref: ${{ github.ref }}
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: python -m pip install --upgrade pip && pip install -r requirements.txt
    - name: Crawl feed
      working-directory: ./
      run: python main.py -i $id
    - name: Upload crawl data as artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.id }}_data
        path: ${{ env.id}}.json
  crawl_kcpl1:
    env:
      id: kcpl1
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
        - '3.8'
    steps:
    - name: checkout
      uses: actions/checkout@v3
      with:
        ref: ${{ github.ref }}
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: python -m pip install --upgrade pip && pip install -r requirements.txt
    - name: Crawl feed
      working-directory: ./
      run: python main.py -i $id
    - name: Upload crawl data as artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.id }}_data
        path: ${{ env.id}}.json
  crawl_kcpl2:
    env:
      id: kcpl2
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
        - '3.8'
    steps:
    - name: checkout
      uses: actions/checkout@v3
      with:
        ref: ${{ github.ref }}
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: python -m pip install --upgrade pip && pip install -r requirements.txt
    - name: Crawl feed
      working-directory: ./
      run: python main.py -i $id
    - name: Upload crawl data as artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.id }}_data
        path: ${{ env.id}}.json
  crawl_umkc:
    env:
      id: umkc
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
        - '3.8'
    steps:
    - name: checkout
      uses: actions/checkout@v3
      with:
        ref: ${{ github.ref }}
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: python -m pip install --upgrade pip && pip install -r requirements.txt
    - name: Crawl feed
      working-directory: ./
      run: python main.py -i $id
    - name: Upload crawl data as artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.id }}_data
        path: ${{ env.id}}.json
  crawl_stlpl:
    env:
      id: stlpl
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
        - '3.8'
    steps:
    - name: checkout
      uses: actions/checkout@v3
      with:
        ref: ${{ github.ref }}
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: python -m pip install --upgrade pip && pip install -r requirements.txt
    - name: Crawl feed
      working-directory: ./
      run: python main.py -i $id
    - name: Upload crawl data as artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.id }}_data
        path: ${{ env.id}}.json
  crawl_shsm:
    env:
      id: shsm
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
        - '3.8'
    steps:
    - name: checkout
      uses: actions/checkout@v3
      with:
        ref: ${{ github.ref }}
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: python -m pip install --upgrade pip && pip install -r requirements.txt
    - name: Crawl feed
      working-directory: ./
      run: python main.py -i $id
    - name: Upload crawl data as artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.id }}_data
        path: ${{ env.id}}.json
  crawl_mdh:
    env:
      id: mdh
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
        - '3.8'
    steps:
    - name: checkout
      uses: actions/checkout@v3
      with:
        ref: ${{ github.ref }}
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: python -m pip install --upgrade pip && pip install -r requirements.txt
    - name: Crawl feed
      working-directory: ./
      run: python main.py -i $id
    - name: Upload crawl data as artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.id }}_data
        path: ${{ env.id}}.json
  crawl_slu:
    env:
      id: slu
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
        - '3.8'
    steps:
    - name: checkout
      uses: actions/checkout@v3
      with:
        ref: ${{ github.ref }}
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: python -m pip install --upgrade pip && pip install -r requirements.txt
    - name: Crawl feed
      working-directory: ./
      run: python main.py -i $id
    - name: Upload crawl data as artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.id }}_data
        path: ${{ env.id}}.json
  crawl_umsl:
    env:
      id: umsl
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
        - '3.8'
    steps:
    - name: checkout
      uses: actions/checkout@v3
      with:
        ref: ${{ github.ref }}
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: python -m pip install --upgrade pip && pip install -r requirements.txt
    - name: Crawl feed
      working-directory: ./
      run: python main.py -i $id
    - name: Upload crawl data as artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.id }}_data
        path: ${{ env.id}}.json
  crawl_sgcl:
    env:
      id: sgcl
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
        - '3.8'
    steps:
    - name: checkout
      uses: actions/checkout@v3
      with:
        ref: ${{ github.ref }}
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: python -m pip install --upgrade pip && pip install -r requirements.txt
    - name: Crawl feed
      working-directory: ./
      run: python main.py -i $id
    - name: Upload crawl data as artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.id }}_data
        path: ${{ env.id}}.json
  crawl_wustl1:
    env:
      id: wustl1
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
        - '3.8'
    steps:
    - name: checkout
      uses: actions/checkout@v3
      with:
        ref: ${{ github.ref }}
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: python -m pip install --upgrade pip && pip install -r requirements.txt
    - name: Crawl feed
      working-directory: ./
      run: python main.py -i $id
    - name: Upload crawl data as artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.id }}_data
        path: ${{ env.id}}.json
  crawl_wustl2:
    env:
      id: wustl2
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
        - '3.8'
    steps:
    - name: checkout
      uses: actions/checkout@v3
      with:
        ref: ${{ github.ref }}
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: python -m pip install --upgrade pip && pip install -r requirements.txt
    - name: Crawl feed
      working-directory: ./
      run: python main.py -i $id
    - name: Upload crawl data as artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.id }}_data
        path: ${{ env.id}}.json
  crawl_lhl:
    env:
      id: lhl
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
        - '3.8'
    steps:
    - name: checkout
      uses: actions/checkout@v3
      with:
        ref: ${{ github.ref }}
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: python -m pip install --upgrade pip && pip install -r requirements.txt
    - name: Crawl feed
      working-directory: ./
      run: python main.py -i $id
    - name: Upload crawl data as artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.id }}_data
        path: ${{ env.id}}.json
  crawl_mhm:
    env:
      id: mhm
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
        - '3.8'
    steps:
    - name: checkout
      uses: actions/checkout@v3
      with:
        ref: ${{ github.ref }}
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: python -m pip install --upgrade pip && pip install -r requirements.txt
    - name: Crawl feed
      working-directory: ./
      run: python main.py -i $id
    - name: Upload crawl data as artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.id }}_data
        path: ${{ env.id}}.json
  crawl_drake:
    env:
      id: drake
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
        - '3.8'
    steps:
    - name: checkout
      uses: actions/checkout@v3
      with:
        ref: ${{ github.ref }}
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: python -m pip install --upgrade pip && pip install -r requirements.txt
    - name: Crawl feed
      working-directory: ./
      run: python main.py -i $id
    - name: Upload crawl data as artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.id }}_data
        path: ${{ env.id}}.json
  crawl_grinnell:
    env:
      id: grinnell
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
        - '3.8'
    steps:
    - name: checkout
      uses: actions/checkout@v3
      with:
        ref: ${{ github.ref }}
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: python -m pip install --upgrade pip && pip install -r requirements.txt
    - name: Crawl feed
      working-directory: ./
      run: python main.py -i $id
    - name: Upload crawl data as artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.id }}_data
        path: ${{ env.id}}.json
  crawl_uni:
    env:
      id: uni
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
        - '3.8'
    steps:
    - name: checkout
      uses: actions/checkout@v3
      with:
        ref: ${{ github.ref }}
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: python -m pip install --upgrade pip && pip install -r requirements.txt
    - name: Crawl feed
      working-directory: ./
      run: python main.py -i $id
    - name: Upload crawl data as artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.id }}_data
        path: ${{ env.id}}.json
  combine:
    needs:
    - crawl_frb
    - crawl_msu
    - crawl_kcpl1
    - crawl_kcpl2
    - crawl_umkc
    - crawl_stlpl
    - crawl_shsm
    - crawl_mdh
    - crawl_slu
    - crawl_umsl
    - crawl_sgcl
    - crawl_wustl1
    - crawl_wustl2
    - crawl_lhl
    - crawl_mhm
    - crawl_drake
    - crawl_grinnell
    - crawl_uni
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
        - '3.8'
    steps:
    - name: checkout
      uses: actions/checkout@v3
      with:
        ref: ${{ github.ref }}
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: python -m pip install --upgrade pip && pip install -r requirements.txt
    - name: Download crawls
      uses: actions/download-artifact@v3
      with:
        name: '*_data'
    - name: Combine files
      working-directory: ./
      run: python combine.py
    - name: Upload jsonl as artifact
      uses: actions/upload-artifact@v3
      with:
        name: mohub_ingest
        path: mohub_ingest.jsonl
    - name: Upload ingest report as artifact
      uses: actions/upload-artifact@v3
      with:
        name: ingest_report
        path: report.txt
  upload_s3:
    runs-on: ubuntu-latest
    needs: combine
    strategy:
      matrix:
        python-version:
        - '3.8'
    steps:
    - name: checkout
      uses: actions/checkout@v3
      with:
        ref: ${{ github.ref }}
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: python -m pip install --upgrade pip && pip install -r requirements.txt
    - name: Download jsonl
      uses: actions/download-artifact@v3
      with:
        name: mohub_ingest
    - names: Upload to S3
      env:
        AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
        AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
        S3_BUCKET: ${{ secrets.S3_BUCKET }}
      working-directory: ./
      run: python upload_s3.py
